/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.UUID;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import model.Contact;
import model.Message;
import model.Room;

/**
 *
 * @author bishoy
 */
public class GroupContactPannel extends ContactPanel {

    /**
     * Creates new form GroupContactPannel
     * 
     * 
     */
    public GroupContactPannel(chatCui gui,conversation superConv, Contact cont) {
        super(gui, cont);
        initComponents();
        GroupContactPannel c = this;
        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {

                c.setBackground(new Color(204, 255, 204));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1 && !superConv.getRoom().isGroupChat) {
                    Room room = new Room();
                    room.isGroupChat=true;
                    room.contactVector = superConv.getRoom().contactVector;
                    //room.contactVector.add(new Contact(gui.user.getUserEmail(), TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, null, WIDTH));
                    room.contactVector.add(cont);
                    room.setRoomId(UUID.randomUUID().toString());
                    
                    //boolean found = false;
                    /*for (int i = 0; i < gui.room.rooms_tabs.getTabCount(); i++) {
                        if (((conversation) gui.room.rooms_tabs.getComponent(i)).getRoomId().equals(room.getRoomId())) {
                            found = true;
                            break;
                        }
                    }*/
                    if(!gui.rooms.containsKey(room.getRoomId())){
                        conversation conv = new conversation(gui,room);
                        conv.setRoomId(room.getRoomId());
                        conv.setRoom(room);
                        gui.rooms.put(room.getRoomId(), conv);
                        conv.setVisible(true);
                    }
                    gui.cih.sendMessage(room, new Message(room.getRoomId(), null, "server Message", cont.getName() + " has join the chat group", true));
                    superConv.friendList.contactsPanel.remove(c);
                    superConv.friendList.dispose();
                }
                if (e.getClickCount() == 1 && superConv.getRoom().isGroupChat) {
                    //room.contactVector.add(new Contact(gui.user.getUserEmail(), TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, null, WIDTH));
                    superConv.getRoom().contactVector.add(cont);
                    gui.cih.sendMessage( superConv.getRoom(), new Message( superConv.getRoom().getRoomId(), null, "server Message", cont.getName() + " has join the chat group", true));
                    superConv.friendList.contactsPanel.remove(c);
                    superConv.friendList.dispose();
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                System.out.println("dddhh");
                c.setBackground(new Color(255, 255, 255));
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        state = new javax.swing.JLabel();

        name.setText("name");

        status.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel img;
    public javax.swing.JLabel name;
    public javax.swing.JLabel state;
    public javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
